### ISSUE TITLE
Allow for verification of signature with a set of cards

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#12]
Currently the SDK requires me to pass the exact card used to sign into `decryptTheVerify`. It would be great if I could just pass it all the cards for a sender and it would let me know if any of them matched.

@vadimavdeev could we get this rolled out somewhere soon? I am working on a demo and would like to have this in it already.

**Comment by vadimavdeev** [comment]
@cbetta This is already implemented in version 4.4.0

**Comment by cbetta** [comment]
@vadimavdeev Hmm, pretty sure I just got an error on this. I will check

**Comment by cbetta** [comment]
So when I run this:

```js
api.cards.find(sender)
  .then(function(cards){
    var plainText = key.decryptThenVerify(cipher, cards).toString();
  });
```

I get:

```sh
c {message: "decryptThenVerify expects publicKey argument to be passed.", stack: "VirgilError↵    at l (https://cdn.virgilsecurity.c…c5c60476b6b6bb.js?body=1:85:31↵    at <anonymous>"}message: "decryptThenVerify expects publicKey argument to be passed."stack: "VirgilError↵    at l (https://cdn.virgilsecurity.com/packages/javascript/sdk/4.4.0/virgil-sdk.min.js:1:924)↵    at s (https://cdn.virgilsecurity.com/packages/javascript/sdk/4.4.0/virgil-sdk.min.js:1:897)↵    at Object._ [as decryptThenVerify] (https://cdn.virgilsecurity.com/packages/javascript/sdk/4.4.0/virgil-sdk.min.js:8:5116)↵    at c.decryptThenVerify (https://cdn.virgilsecurity.com/packages/javascript/sdk/4.4.0/virgil-sdk.min.js:28:2485)↵    at http://localhost:5000/assets/channels/chat.self-33ff5751dbc02323a205664f184888a3e0724958924c467339c5c60476b6b6bb.js?body=1:85:31↵    at <anonymous>"__proto__: Error
test:1 Uncaught (in promise) c {message: "decryptThenVerify expects publicKey argument to be passed.", stack: "VirgilError↵    at l (https://cdn.virgilsecurity.c…c5c60476b6b6bb.js?body=1:85:31↵    at <anonymous>"}
```

**Comment by cbetta** [comment]
Where if I pass in one card, it works fine

**Comment by vadimavdeev** [comment]
Yep, that's a bug. It does't work with `VirgilKey`objects. Only `virgil.crypto.decryptThenVerify` supports it. I'm working on a fix right now.

**Comment by cbetta** [comment]
@vadimavdeev awesome. Good to see I wasn't going crazy. Let me know when you u have a fix.

**Comment by vadimavdeev** [comment]
@cbetta We have a fix.
